#
# The simplest possible GitHub Actions workflow.
#

name: Hello world

on:
  # Triggers on push to any branch.
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello-world"
  hello-world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs our our "Hello world" shell script.
      - name: Runs the "Hello world" shell script
        run: ./index.sh
